repos:
- hooks:
  - args:
    - --remove-all-unused-imports
    - --in-place
    id: autoflake
  repo: https://github.com/humitos/mirrors-autoflake
  rev: v1.1
- hooks:
  - id: isort
  repo: https://github.com/timothycrosley/isort
  rev: 5.7.0
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 21.6b0
- hooks:
  - id: flake8
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
